-- ============================================================================
-- Heard Back: catalogue breadth, migration 017
-- ============================================================================
--
-- ADDITIVE. Nothing is updated or deleted.
--
-- WHY THIS EXISTS.
--
-- The catalogue had 61 firms. A student compared it to the established UK
-- finance tracker, which lists 413, and the comparison was not close. The
-- cause was a design mistake of mine, not an oversight:
--
--   I only ever added firms whose ATS I could poll.
--
-- 21 firms have a pollable source, so the catalogue grew to roughly that plus
-- the ones named in the source chat, and stopped. But SEARCH_ROLES_SQL never
-- filtered on opened_at - it only sorts detected roles first. A role with no
-- detected opening date has always been listable and loggable. I had conflated
-- "we can detect when this opens" with "we can let someone log a stage against
-- it", and they are not the same requirement. Detection is a feature of the
-- feed. The catalogue only has to name the thing accurately.
--
-- That distinction matters for this product specifically. Heard Back does not
-- tell you when something opens - it tells you whether anyone has heard back.
-- That answer comes from students, not from polling. A firm with no ATS source
-- is fully functional here: people log, the denominator builds, the pulse
-- works. Excluding those firms cost us the entire long tail for no benefit.
--
-- WHAT IS AND IS NOT ASSERTED HERE.
--
-- Every row below asserts one thing: this firm runs a London summer programme
-- that UK students apply to. That is a fact about the world.
--
-- No opening date, closing date, stage, process or test vendor is set by this
-- migration. Those are the parts a tracker earns by checking, and they are
-- also the parts that are someone else's editorial work. opened_at stays null
-- until our own poller sees a posting, or a student logs a stage. An empty
-- date column is honest; a borrowed one is not.
--
-- The non-finance long tail was deliberately skipped. The audience for this
-- site is a group chat of students applying to banking, quant and consulting.
-- Adding supermarkets and utilities would make the number bigger and the site
-- worse.
-- ============================================================================


insert into firms (slug, name, name_norm, category, tier)
select slugify(v.name), v.name, normalise_name(v.name), v.category, v.tier
from (values
  ('Ardea Partners', 'ib_markets', 'elite_boutique'),
  ('Greenhill', 'ib_markets', 'elite_boutique'),
  ('LionTree', 'ib_markets', 'elite_boutique'),
  ('Raine Group', 'ib_markets', 'elite_boutique'),
  ('ABN AMRO', 'ib_markets', 'middle_market'),
  ('Alantra', 'ib_markets', 'middle_market'),
  ('BBVA', 'ib_markets', 'middle_market'),
  ('BMO Capital Markets', 'ib_markets', 'middle_market'),
  ('BTIG', 'ib_markets', 'middle_market'),
  ('Baird', 'ib_markets', 'middle_market'),
  ('Berenberg', 'ib_markets', 'middle_market'),
  ('CIBC', 'ib_markets', 'middle_market'),
  ('Campbell Lutyens', 'ib_markets', 'middle_market'),
  ('Crédit Agricole', 'ib_markets', 'middle_market'),
  ('DC Advisory', 'ib_markets', 'middle_market'),
  ('Eastdil Secured', 'ib_markets', 'middle_market'),
  ('Fenchurch Advisory', 'ib_markets', 'middle_market'),
  ('GP Bullhound', 'ib_markets', 'middle_market'),
  ('Gleacher Shacklock', 'ib_markets', 'middle_market'),
  ('Guggenheim Partners', 'ib_markets', 'middle_market'),
  ('Handelsbanken', 'ib_markets', 'middle_market'),
  ('Harris Williams', 'ib_markets', 'middle_market'),
  ('Investec', 'ib_markets', 'middle_market'),
  ('Leerink Partners', 'ib_markets', 'middle_market'),
  ('Lincoln International', 'ib_markets', 'middle_market'),
  ('Lloyds Banking Group', 'ib_markets', 'middle_market'),
  ('MUFG', 'ib_markets', 'middle_market'),
  ('NatWest Markets', 'ib_markets', 'middle_market'),
  ('National Bank of Canada', 'ib_markets', 'middle_market'),
  ('Panmure Liberum', 'ib_markets', 'middle_market'),
  ('Peel Hunt', 'ib_markets', 'middle_market'),
  ('Piper Sandler', 'ib_markets', 'middle_market'),
  ('Raymond James', 'ib_markets', 'middle_market'),
  ('Rede Partners', 'ib_markets', 'middle_market'),
  ('STJ Advisors', 'ib_markets', 'middle_market'),
  ('Scotiabank', 'ib_markets', 'middle_market'),
  ('Société Générale', 'ib_markets', 'middle_market'),
  ('Stifel', 'ib_markets', 'middle_market'),
  ('TD Securities', 'ib_markets', 'middle_market'),
  ('Wells Fargo', 'ib_markets', 'middle_market'),
  ('William Blair', 'ib_markets', 'middle_market'),
  ('Zeus Capital', 'ib_markets', 'middle_market'),
  ('Aquatic Capital Management', 'quant', 'prop_quant'),
  ('Aspect Capital', 'quant', 'prop_quant'),
  ('BMLL', 'quant', 'prop_quant'),
  ('Cboe Global Markets', 'quant', 'prop_quant'),
  ('Chicago Trading Company', 'quant', 'prop_quant'),
  ('DV Trading', 'quant', 'prop_quant'),
  ('Da Vinci Trading', 'quant', 'prop_quant'),
  ('ExodusPoint', 'quant', 'prop_quant'),
  ('GSA Capital', 'quant', 'prop_quant'),
  ('Liquidnet', 'quant', 'prop_quant'),
  ('Mako Trading', 'quant', 'prop_quant'),
  ('MarketAxess', 'quant', 'prop_quant'),
  ('Quadrature', 'quant', 'prop_quant'),
  ('Quantbot Technologies', 'quant', 'prop_quant'),
  ('Teza Technologies', 'quant', 'prop_quant'),
  ('Tower Research Capital', 'quant', 'prop_quant'),
  ('Virtu Financial', 'quant', 'prop_quant'),
  ('Wintermute', 'quant', 'prop_quant'),
  ('StoneX', 'quant', 'prop_quant'),
  ('Javelin Global Commodities', 'quant', 'prop_quant'),
  ('iSAM', 'quant', 'prop_quant'),
  ('Gunvor', 'quant', 'prop_quant'),
  ('Vitol', 'quant', 'prop_quant'),
  ('Trafigura', 'quant', 'prop_quant'),
  ('Mercuria', 'quant', 'prop_quant'),
  ('BP', 'quant', 'prop_quant'),
  ('Shell', 'quant', 'prop_quant'),
  ('Equinor', 'quant', 'prop_quant'),
  ('RWE', 'quant', 'prop_quant'),
  ('Ares Management', 'asset_management', 'buyside'),
  ('Balyasny Asset Management', 'asset_management', 'buyside'),
  ('Brevan Howard', 'asset_management', 'buyside'),
  ('CD&R', 'asset_management', 'buyside'),
  ('Capstone Investment Advisors', 'asset_management', 'buyside'),
  ('Capula Investment Management', 'asset_management', 'buyside'),
  ('Caxton Associates', 'asset_management', 'buyside'),
  ('D.E. Shaw', 'asset_management', 'buyside'),
  ('EQT', 'asset_management', 'buyside'),
  ('General Atlantic', 'asset_management', 'buyside'),
  ('GIC', 'asset_management', 'buyside'),
  ('Hamilton Lane', 'asset_management', 'buyside'),
  ('Hayfin Capital Management', 'asset_management', 'buyside'),
  ('LMR Partners', 'asset_management', 'buyside'),
  ('Neuberger Berman', 'asset_management', 'buyside'),
  ('Oak Hill Advisors', 'asset_management', 'buyside'),
  ('Rokos Capital Management', 'asset_management', 'buyside'),
  ('Schonfeld', 'asset_management', 'buyside'),
  ('Sixth Street', 'asset_management', 'buyside'),
  ('Sona Asset Management', 'asset_management', 'buyside'),
  ('StepStone Group', 'asset_management', 'buyside'),
  ('Temasek', 'asset_management', 'buyside'),
  ('Verition Fund Management', 'asset_management', 'buyside'),
  ('Cinven', 'asset_management', 'buyside'),
  ('Permira', 'asset_management', 'buyside'),
  ('Apollo Global Management', 'asset_management', 'buyside'),
  ('Carlyle', 'asset_management', 'buyside'),
  ('TPG', 'asset_management', 'buyside'),
  ('Warburg Pincus', 'asset_management', 'buyside'),
  ('Bridgepoint', 'asset_management', 'buyside'),
  ('PAI Partners', 'asset_management', 'buyside'),
  ('InfraRed Capital Partners', 'asset_management', 'buyside'),
  ('Patrizia', 'asset_management', 'buyside'),
  ('Aberdeen Group', 'asset_management', 'buyside'),
  ('AllianceBernstein', 'asset_management', 'buyside'),
  ('Barings', 'asset_management', 'buyside'),
  ('Capital Group', 'asset_management', 'buyside'),
  ('Columbia Threadneedle Investments', 'asset_management', 'buyside'),
  ('DWS', 'asset_management', 'buyside'),
  ('Dimensional Fund Advisors', 'asset_management', 'buyside'),
  ('Fidelity International', 'asset_management', 'buyside'),
  ('Fidelity Investments', 'asset_management', 'buyside'),
  ('Franklin Templeton', 'asset_management', 'buyside'),
  ('Julius Baer', 'asset_management', 'buyside'),
  ('Lazard Asset Management', 'asset_management', 'buyside'),
  ('Legal & General', 'asset_management', 'buyside'),
  ('M&G', 'asset_management', 'buyside'),
  ('MFS', 'asset_management', 'buyside'),
  ('Norges Bank', 'asset_management', 'buyside'),
  ('Northern Trust', 'asset_management', 'buyside'),
  ('Nuveen', 'asset_management', 'buyside'),
  ('PGIM', 'asset_management', 'buyside'),
  ('PIMCO', 'asset_management', 'buyside'),
  ('Principal Asset Management', 'asset_management', 'buyside'),
  ('Redburn', 'asset_management', 'buyside'),
  ('Schroders', 'asset_management', 'buyside'),
  ('Soros Fund Management', 'asset_management', 'buyside'),
  ('Vanguard', 'asset_management', 'buyside'),
  ('Walter Scott', 'asset_management', 'buyside'),
  ('7IM', 'asset_management', 'buyside'),
  ('Rothesay', 'asset_management', 'buyside'),
  ('Pictet Asset Management', 'asset_management', 'buyside'),
  ('Cambridge Associates', 'asset_management', 'buyside'),
  ('Orbis', 'asset_management', 'buyside'),
  ('Alvarez & Marsal', 'consulting', 'consulting'),
  ('Analysys Mason', 'consulting', 'consulting'),
  ('Baringa', 'consulting', 'consulting'),
  ('Capgemini', 'consulting', 'consulting'),
  ('Charles River Associates', 'consulting', 'consulting'),
  ('Compass Lexecon', 'consulting', 'consulting'),
  ('EY-Parthenon', 'consulting', 'consulting'),
  ('FTI Consulting', 'consulting', 'consulting'),
  ('Guidehouse', 'consulting', 'consulting'),
  ('Interpath Advisory', 'consulting', 'consulting'),
  ('Korn Ferry', 'consulting', 'consulting'),
  ('L.E.K. Consulting', 'consulting', 'consulting'),
  ('NERA', 'consulting', 'consulting'),
  ('OC&C', 'consulting', 'consulting'),
  ('Oxera', 'consulting', 'consulting'),
  ('Roland Berger', 'consulting', 'consulting'),
  ('Simon-Kucher', 'consulting', 'consulting'),
  ('Teneo', 'consulting', 'consulting'),
  ('ZS', 'consulting', 'consulting'),
  ('Accuracy', 'consulting', 'consulting'),
  ('Alpha FMC', 'consulting', 'consulting'),
  ('Arthur D. Little', 'consulting', 'consulting'),
  ('Deloitte', 'consulting', 'consulting'),
  ('EY', 'consulting', 'consulting'),
  ('KPMG', 'consulting', 'consulting'),
  ('PwC', 'consulting', 'consulting'),
  ('Grant Thornton', 'consulting', 'consulting'),
  ('BDO', 'consulting', 'consulting'),
  ('Forvis Mazars', 'consulting', 'consulting'),
  ('RSM', 'consulting', 'consulting'),
  ('Bank of England', 'asset_management', 'middle_market'),
  ('Financial Conduct Authority', 'asset_management', 'middle_market'),
  ('EBRD', 'ib_markets', 'middle_market'),
  ('London Stock Exchange Group', 'data_ai', 'tech'),
  ('S&P Global', 'data_ai', 'tech'),
  ('Moody''s', 'data_ai', 'tech'),
  ('FactSet', 'data_ai', 'tech'),
  ('ICE', 'quant', 'tech'),
  ('Tradeweb', 'quant', 'tech'),
  ('Revolut', 'data_ai', 'tech'),
  ('Capital One', 'data_ai', 'tech'),
  ('Marsh McLennan', 'consulting', 'consulting'),
  ('WTW', 'consulting', 'consulting'),
  ('Aon', 'consulting', 'consulting'),
  ('Visa', 'data_ai', 'tech'),
  ('American Express', 'data_ai', 'tech')
) as v(name, category, tier)
on conflict (name_norm) do nothing;

insert into roles
  (firm_id, programme_id, division, division_norm, location, location_norm,
   cycle, slug, category)
select f.id, p.id, v.division, normalise_name(v.division),
       'London', normalise_name('London'), 'Summer 2027',
       f.slug || '-' || slugify(v.division) || '-london-summer-2027',
       v.category
from (values
  ('Ardea Partners', 'Investment Banking', 'ib_markets'),
  ('Greenhill', 'Investment Banking', 'ib_markets'),
  ('LionTree', 'Investment Banking', 'ib_markets'),
  ('Raine Group', 'Investment Banking', 'ib_markets'),
  ('ABN AMRO', 'Investment Banking', 'ib_markets'),
  ('Alantra', 'Investment Banking', 'ib_markets'),
  ('BBVA', 'Investment Banking', 'ib_markets'),
  ('BMO Capital Markets', 'Investment Banking', 'ib_markets'),
  ('BTIG', 'Investment Banking', 'ib_markets'),
  ('Baird', 'Investment Banking', 'ib_markets'),
  ('Berenberg', 'Investment Banking', 'ib_markets'),
  ('CIBC', 'Investment Banking', 'ib_markets'),
  ('Campbell Lutyens', 'Investment Banking', 'ib_markets'),
  ('Crédit Agricole', 'Investment Banking', 'ib_markets'),
  ('DC Advisory', 'Investment Banking', 'ib_markets'),
  ('Eastdil Secured', 'Investment Banking', 'ib_markets'),
  ('Fenchurch Advisory', 'Investment Banking', 'ib_markets'),
  ('GP Bullhound', 'Investment Banking', 'ib_markets'),
  ('Gleacher Shacklock', 'Investment Banking', 'ib_markets'),
  ('Guggenheim Partners', 'Investment Banking', 'ib_markets'),
  ('Handelsbanken', 'Investment Banking', 'ib_markets'),
  ('Harris Williams', 'Investment Banking', 'ib_markets'),
  ('Investec', 'Investment Banking', 'ib_markets'),
  ('Leerink Partners', 'Investment Banking', 'ib_markets'),
  ('Lincoln International', 'Investment Banking', 'ib_markets'),
  ('Lloyds Banking Group', 'Investment Banking', 'ib_markets'),
  ('MUFG', 'Investment Banking', 'ib_markets'),
  ('NatWest Markets', 'Investment Banking', 'ib_markets'),
  ('National Bank of Canada', 'Investment Banking', 'ib_markets'),
  ('Panmure Liberum', 'Investment Banking', 'ib_markets'),
  ('Peel Hunt', 'Investment Banking', 'ib_markets'),
  ('Piper Sandler', 'Investment Banking', 'ib_markets'),
  ('Raymond James', 'Investment Banking', 'ib_markets'),
  ('Rede Partners', 'Investment Banking', 'ib_markets'),
  ('STJ Advisors', 'Investment Banking', 'ib_markets'),
  ('Scotiabank', 'Investment Banking', 'ib_markets'),
  ('Société Générale', 'Investment Banking', 'ib_markets'),
  ('Stifel', 'Investment Banking', 'ib_markets'),
  ('TD Securities', 'Investment Banking', 'ib_markets'),
  ('Wells Fargo', 'Investment Banking', 'ib_markets'),
  ('William Blair', 'Investment Banking', 'ib_markets'),
  ('Zeus Capital', 'Investment Banking', 'ib_markets'),
  ('Aquatic Capital Management', 'Quantitative Trading', 'quant'),
  ('Aspect Capital', 'Quantitative Trading', 'quant'),
  ('BMLL', 'Quantitative Trading', 'quant'),
  ('Cboe Global Markets', 'Quantitative Trading', 'quant'),
  ('Chicago Trading Company', 'Quantitative Trading', 'quant'),
  ('DV Trading', 'Quantitative Trading', 'quant'),
  ('Da Vinci Trading', 'Quantitative Trading', 'quant'),
  ('ExodusPoint', 'Quantitative Trading', 'quant'),
  ('GSA Capital', 'Quantitative Trading', 'quant'),
  ('Liquidnet', 'Quantitative Trading', 'quant'),
  ('Mako Trading', 'Quantitative Trading', 'quant'),
  ('MarketAxess', 'Quantitative Trading', 'quant'),
  ('Quadrature', 'Quantitative Trading', 'quant'),
  ('Quantbot Technologies', 'Quantitative Trading', 'quant'),
  ('Teza Technologies', 'Quantitative Trading', 'quant'),
  ('Tower Research Capital', 'Quantitative Trading', 'quant'),
  ('Virtu Financial', 'Quantitative Trading', 'quant'),
  ('Wintermute', 'Quantitative Trading', 'quant'),
  ('StoneX', 'Quantitative Trading', 'quant'),
  ('Javelin Global Commodities', 'Quantitative Trading', 'quant'),
  ('iSAM', 'Quantitative Trading', 'quant'),
  ('Gunvor', 'Quantitative Trading', 'quant'),
  ('Vitol', 'Quantitative Trading', 'quant'),
  ('Trafigura', 'Quantitative Trading', 'quant'),
  ('Mercuria', 'Quantitative Trading', 'quant'),
  ('BP', 'Trading & Shipping', 'quant'),
  ('Shell', 'Trading & Supply', 'quant'),
  ('Equinor', 'Trading', 'quant'),
  ('RWE', 'Energy Trading', 'quant'),
  ('Ares Management', 'Investment Team', 'asset_management'),
  ('Balyasny Asset Management', 'Investment Team', 'asset_management'),
  ('Brevan Howard', 'Investment Team', 'asset_management'),
  ('CD&R', 'Investment Team', 'asset_management'),
  ('Capstone Investment Advisors', 'Investment Team', 'asset_management'),
  ('Capula Investment Management', 'Investment Team', 'asset_management'),
  ('Caxton Associates', 'Investment Team', 'asset_management'),
  ('D.E. Shaw', 'Investment Team', 'asset_management'),
  ('EQT', 'Investment Team', 'asset_management'),
  ('General Atlantic', 'Investment Team', 'asset_management'),
  ('GIC', 'Investment Team', 'asset_management'),
  ('Hamilton Lane', 'Investment Team', 'asset_management'),
  ('Hayfin Capital Management', 'Investment Team', 'asset_management'),
  ('LMR Partners', 'Investment Team', 'asset_management'),
  ('Neuberger Berman', 'Investment Team', 'asset_management'),
  ('Oak Hill Advisors', 'Investment Team', 'asset_management'),
  ('Rokos Capital Management', 'Investment Team', 'asset_management'),
  ('Schonfeld', 'Investment Team', 'asset_management'),
  ('Sixth Street', 'Investment Team', 'asset_management'),
  ('Sona Asset Management', 'Investment Team', 'asset_management'),
  ('StepStone Group', 'Investment Team', 'asset_management'),
  ('Temasek', 'Investment Team', 'asset_management'),
  ('Verition Fund Management', 'Investment Team', 'asset_management'),
  ('Cinven', 'Investment Team', 'asset_management'),
  ('Permira', 'Investment Team', 'asset_management'),
  ('Apollo Global Management', 'Investment Team', 'asset_management'),
  ('Carlyle', 'Investment Team', 'asset_management'),
  ('TPG', 'Investment Team', 'asset_management'),
  ('Warburg Pincus', 'Investment Team', 'asset_management'),
  ('Bridgepoint', 'Investment Team', 'asset_management'),
  ('PAI Partners', 'Investment Team', 'asset_management'),
  ('InfraRed Capital Partners', 'Investment Team', 'asset_management'),
  ('Patrizia', 'Investment Team', 'asset_management'),
  ('Aberdeen Group', 'Investment Management', 'asset_management'),
  ('AllianceBernstein', 'Investment Management', 'asset_management'),
  ('Barings', 'Investment Management', 'asset_management'),
  ('Capital Group', 'Investment Management', 'asset_management'),
  ('Columbia Threadneedle Investments', 'Investment Management', 'asset_management'),
  ('DWS', 'Investment Management', 'asset_management'),
  ('Dimensional Fund Advisors', 'Investment Management', 'asset_management'),
  ('Fidelity International', 'Investment Management', 'asset_management'),
  ('Fidelity Investments', 'Investment Management', 'asset_management'),
  ('Franklin Templeton', 'Investment Management', 'asset_management'),
  ('Julius Baer', 'Investment Management', 'asset_management'),
  ('Lazard Asset Management', 'Investment Management', 'asset_management'),
  ('Legal & General', 'Investment Management', 'asset_management'),
  ('M&G', 'Investment Management', 'asset_management'),
  ('MFS', 'Investment Management', 'asset_management'),
  ('Norges Bank', 'Investment Management', 'asset_management'),
  ('Northern Trust', 'Investment Management', 'asset_management'),
  ('Nuveen', 'Investment Management', 'asset_management'),
  ('PGIM', 'Investment Management', 'asset_management'),
  ('PIMCO', 'Investment Management', 'asset_management'),
  ('Principal Asset Management', 'Investment Management', 'asset_management'),
  ('Redburn', 'Investment Management', 'asset_management'),
  ('Schroders', 'Investment Management', 'asset_management'),
  ('Soros Fund Management', 'Investment Management', 'asset_management'),
  ('Vanguard', 'Investment Management', 'asset_management'),
  ('Walter Scott', 'Investment Management', 'asset_management'),
  ('7IM', 'Investment Management', 'asset_management'),
  ('Rothesay', 'Investment Management', 'asset_management'),
  ('Pictet Asset Management', 'Investment Management', 'asset_management'),
  ('Cambridge Associates', 'Investment Management', 'asset_management'),
  ('Orbis', 'Investment Management', 'asset_management'),
  ('Alvarez & Marsal', 'Consulting', 'consulting'),
  ('Analysys Mason', 'Consulting', 'consulting'),
  ('Baringa', 'Consulting', 'consulting'),
  ('Capgemini', 'Consulting', 'consulting'),
  ('Charles River Associates', 'Consulting', 'consulting'),
  ('Compass Lexecon', 'Consulting', 'consulting'),
  ('EY-Parthenon', 'Consulting', 'consulting'),
  ('FTI Consulting', 'Consulting', 'consulting'),
  ('Guidehouse', 'Consulting', 'consulting'),
  ('Interpath Advisory', 'Consulting', 'consulting'),
  ('Korn Ferry', 'Consulting', 'consulting'),
  ('L.E.K. Consulting', 'Consulting', 'consulting'),
  ('NERA', 'Consulting', 'consulting'),
  ('OC&C', 'Consulting', 'consulting'),
  ('Oxera', 'Consulting', 'consulting'),
  ('Roland Berger', 'Consulting', 'consulting'),
  ('Simon-Kucher', 'Consulting', 'consulting'),
  ('Teneo', 'Consulting', 'consulting'),
  ('ZS', 'Consulting', 'consulting'),
  ('Accuracy', 'Consulting', 'consulting'),
  ('Alpha FMC', 'Consulting', 'consulting'),
  ('Arthur D. Little', 'Consulting', 'consulting'),
  ('Deloitte', 'Deals & Advisory', 'consulting'),
  ('Deloitte', 'Audit', 'consulting'),
  ('EY', 'Deals & Advisory', 'consulting'),
  ('EY', 'Audit', 'consulting'),
  ('KPMG', 'Deals & Advisory', 'consulting'),
  ('KPMG', 'Audit', 'consulting'),
  ('PwC', 'Deals & Advisory', 'consulting'),
  ('PwC', 'Audit', 'consulting'),
  ('Grant Thornton', 'Deals & Advisory', 'consulting'),
  ('Grant Thornton', 'Audit', 'consulting'),
  ('BDO', 'Deals & Advisory', 'consulting'),
  ('BDO', 'Audit', 'consulting'),
  ('Forvis Mazars', 'Deals & Advisory', 'consulting'),
  ('Forvis Mazars', 'Audit', 'consulting'),
  ('RSM', 'Deals & Advisory', 'consulting'),
  ('RSM', 'Audit', 'consulting'),
  ('Bank of England', 'Markets & Analysis', 'asset_management'),
  ('Financial Conduct Authority', 'Graduate Programme', 'asset_management'),
  ('EBRD', 'Banking', 'ib_markets'),
  ('London Stock Exchange Group', 'Graduate Programme', 'data_ai'),
  ('S&P Global', 'Market Intelligence', 'data_ai'),
  ('Moody''s', 'Analytics', 'data_ai'),
  ('FactSet', 'Analytics', 'data_ai'),
  ('ICE', 'Trading & Clearing', 'quant'),
  ('Tradeweb', 'Markets', 'quant'),
  ('Revolut', 'Analytics', 'data_ai'),
  ('Revolut', 'Software Engineering', 'swe'),
  ('Capital One', 'Data Science', 'data_ai'),
  ('Capital One', 'Business Analyst', 'data_ai'),
  ('Marsh McLennan', 'Consulting', 'consulting'),
  ('WTW', 'Consulting', 'consulting'),
  ('Aon', 'Consulting', 'consulting'),
  ('Visa', 'Data & Analytics', 'data_ai'),
  ('American Express', 'Analytics', 'data_ai')
) as v(firm_name, division, category)
join firms f      on f.name_norm = normalise_name(v.firm_name)
join programmes p on p.slug = 'summer'
on conflict (firm_id, programme_id, division_norm, location_norm, cycle)
  do nothing;

-- Abbreviations people actually type into the search box.
insert into aliases (kind, alias_norm, firm_id)
select 'firm', normalise_name(v.alias), f.id
from (values
  ('Greenhill & Co', 'Greenhill'),
  ('The Raine Group', 'Raine Group'),
  ('BMO', 'BMO Capital Markets'),
  ('Robert W. Baird', 'Baird'),
  ('CIBC Capital Markets', 'CIBC'),
  ('Credit Agricole', 'Crédit Agricole'),
  ('CACIB', 'Crédit Agricole'),
  ('Guggenheim', 'Guggenheim Partners'),
  ('Lloyds', 'Lloyds Banking Group'),
  ('Mitsubishi UFJ', 'MUFG'),
  ('NatWest', 'NatWest Markets'),
  ('RBS', 'NatWest Markets'),
  ('NBC', 'National Bank of Canada'),
  ('Panmure', 'Panmure Liberum'),
  ('Liberum', 'Panmure Liberum'),
  ('Scotia', 'Scotiabank'),
  ('Societe Generale', 'Société Générale'),
  ('SocGen', 'Société Générale'),
  ('SG', 'Société Générale'),
  ('TD', 'TD Securities'),
  ('WF', 'Wells Fargo'),
  ('Aquatic', 'Aquatic Capital Management'),
  ('BMLL Technologies', 'BMLL'),
  ('Cboe', 'Cboe Global Markets'),
  ('CTC', 'Chicago Trading Company'),
  ('Da Vinci', 'Da Vinci Trading'),
  ('GSA', 'GSA Capital'),
  ('Mako', 'Mako Trading'),
  ('Quadrature Capital', 'Quadrature'),
  ('Quantbot', 'Quantbot Technologies'),
  ('Teza', 'Teza Technologies'),
  ('Tower Research', 'Tower Research Capital'),
  ('Tower', 'Tower Research Capital'),
  ('Virtu', 'Virtu Financial'),
  ('Javelin', 'Javelin Global Commodities'),
  ('iSAM Securities', 'iSAM'),
  ('BP Trading', 'BP'),
  ('Ares', 'Ares Management'),
  ('Balyasny', 'Balyasny Asset Management'),
  ('BAM', 'Balyasny Asset Management'),
  ('Clayton Dubilier & Rice', 'CD&R'),
  ('Capstone', 'Capstone Investment Advisors'),
  ('Capula', 'Capula Investment Management'),
  ('Caxton', 'Caxton Associates'),
  ('DE Shaw', 'D.E. Shaw'),
  ('D E Shaw', 'D.E. Shaw'),
  ('DESCO', 'D.E. Shaw'),
  ('Hayfin', 'Hayfin Capital Management'),
  ('LMR', 'LMR Partners'),
  ('Oak Hill', 'Oak Hill Advisors'),
  ('Rokos', 'Rokos Capital Management'),
  ('Sona', 'Sona Asset Management'),
  ('StepStone', 'StepStone Group'),
  ('Verition', 'Verition Fund Management'),
  ('Apollo', 'Apollo Global Management'),
  ('The Carlyle Group', 'Carlyle'),
  ('PAI', 'PAI Partners'),
  ('InfraRed', 'InfraRed Capital Partners'),
  ('Aberdeen', 'Aberdeen Group'),
  ('abrdn', 'Aberdeen Group'),
  ('AB', 'AllianceBernstein'),
  ('Columbia Threadneedle', 'Columbia Threadneedle Investments'),
  ('Threadneedle', 'Columbia Threadneedle Investments'),
  ('Dimensional', 'Dimensional Fund Advisors'),
  ('DFA', 'Dimensional Fund Advisors'),
  ('FIL', 'Fidelity International'),
  ('Lazard AM', 'Lazard Asset Management'),
  ('L&G', 'Legal & General'),
  ('LGIM', 'Legal & General'),
  ('M and G', 'M&G'),
  ('NBIM', 'Norges Bank'),
  ('Principal', 'Principal Asset Management'),
  ('Redburn Atlantic', 'Redburn'),
  ('Soros', 'Soros Fund Management'),
  ('Seven Investment Management', '7IM'),
  ('Pictet', 'Pictet Asset Management'),
  ('Orbis Investments', 'Orbis'),
  ('A&M', 'Alvarez & Marsal'),
  ('Alvarez and Marsal', 'Alvarez & Marsal'),
  ('Baringa Partners', 'Baringa'),
  ('CRA', 'Charles River Associates'),
  ('EY Parthenon', 'EY-Parthenon'),
  ('Parthenon', 'EY-Parthenon'),
  ('FTI', 'FTI Consulting'),
  ('Interpath', 'Interpath Advisory'),
  ('LEK', 'L.E.K. Consulting'),
  ('L E K', 'L.E.K. Consulting'),
  ('NERA Economic Consulting', 'NERA'),
  ('OC&C Strategy Consultants', 'OC&C'),
  ('Simon Kucher', 'Simon-Kucher'),
  ('ZS Associates', 'ZS'),
  ('Alpha', 'Alpha FMC'),
  ('ADL', 'Arthur D. Little'),
  ('Ernst & Young', 'EY'),
  ('Ernst and Young', 'EY'),
  ('PriceWaterhouseCoopers', 'PwC'),
  ('Price Waterhouse Coopers', 'PwC'),
  ('GT', 'Grant Thornton'),
  ('BDO Global', 'BDO'),
  ('Mazars', 'Forvis Mazars'),
  ('BoE', 'Bank of England'),
  ('FCA', 'Financial Conduct Authority'),
  ('European Bank for Reconstruction and Development', 'EBRD'),
  ('LSEG', 'London Stock Exchange Group'),
  ('LSE Group', 'London Stock Exchange Group'),
  ('S and P Global', 'S&P Global'),
  ('SP Global', 'S&P Global'),
  ('Moodys', 'Moody''s'),
  ('Intercontinental Exchange', 'ICE'),
  ('Marsh & McLennan', 'Marsh McLennan'),
  ('Mercer', 'Marsh McLennan'),
  ('Willis Towers Watson', 'WTW'),
  ('Amex', 'American Express')
) as v(alias, firm_name)
join firms f on f.name_norm = normalise_name(v.firm_name)
on conflict do nothing;
